### ISSUE TITLE
проблема со статусами

### ISSUE THREAD

**Issue by skomaroh** [buglloc/brick#1]
Есть у нас уведомления, по DBus передается сигнал, всё в порядке.
Приходит нам сообщение, также всё передается.

В кирпиче читаем сообщение, но по DBus передается сигнал отсутствия событий уведомлений, хотя уведомления по прежнему не прочитаны.

**Comment by buglloc** [comment]
Thanks!
Пожалуйста, попробуй в следующей сборке (0.1.15.29), когда соберу. Должно быть нормально (пришлось правда немного поигнорить IM), если что - пиши;-)
