### ISSUE TITLE
windows version

### ISSUE THREAD

**Issue by toFlash** [buglloc/brick#10]
приветствую, не планируется выпуск альтернативного клиента только под винду?

**Comment by buglloc** [comment]
Приветствую, а чем не устраивает официальный?:-)

**Comment by toFlash** [comment]
Последней каплей стал последний релиз, который заглючил у многих пользователей, сразу 3 ошибки вылезло
1 ошибка ssl
2 кирилические логины аброкадаброй
3 пустое окошко чата, которое надо прокрутить вверх хитрым способом, зажав колесико мыши и протянув вверх
+ есть ряд хотелок, например управление уведомлениями, длительностью отображения, местом и пр

**Comment by toFlash** [comment]
а на основе какой документации вы делали свой билд? где можно почитать?

**Comment by buglloc** [comment]
>> Последней каплей стал последний релиз, который заглючил у многих пользователей, сразу 3 ошибки вылезло

Случается, не боги горшки обжигают:-) Что же касается кастомизации, то и в кирпиче некоторые вещи можно кастомизировать только костылями, ибо Brick, как и офф. версия, это в первую очередь гибридное приложение и многим функционалом управляет код Битрикса не отчитываясь перед нативной частью "зачем да почему". Так, например, управление нотификациями на стороне нативной части (а в случае с Brick так и вовсе окружения, ибо используются системный уведомления), а вот кастомизировать тот же список контактов без monkey patching'а JS кода уже не выйдет:-(

>> а на основе какой документации вы делали свой билд? где можно почитать?

Увы, никакой подобной документации не существует:-( Я просто в виду специфики своей работы (security guy at Bitrix) имел представление о работе официального приложения, поэтому мне было легче. Не пробовали задавать вопрос самому Битриксу? Может на идеях? Вдруг решат отдать в OpenSource;-)

**Comment by buglloc** [comment]
Что же касается сабжа - разработка версии под Windows не планировалась. Мне не интересна эта платформа, да и если честно, я очень давно под неё ничего не писал.

**Comment by toFlash** [comment]
спасибо за развернутый ответ, удачи с проектом!
