### ISSUE TITLE
поддержка высокого разрешения (например, 3200x1800 WQXGA+)

### ISSUE THREAD

**Issue by MikhailBarsukov** [buglloc/brick#12]
Все больше и больше устройств в арсенале с FHD и выше разрешением и brick сейчас работает в таком разрешении не совсем корректно.
![brick_screen](https://cloud.githubusercontent.com/assets/2105413/7628184/fb962f58-fa28-11e4-8bfa-7272f2823cf9.png)

**Comment by buglloc** [comment]
Да в GNU/Linux пока не так все гладко с поддержкой "scale factor" в виду разных неуклюжих причин... Тут проблему нужно разделить на две части:

 1. Проблемы связанные с нативными окнами (как на скриншоте) - я попробую решить в ближайшем будущем. Боюсь правда, что с GTK2  только какими-то костылями, ибо офф. поддержка появилась только в GTK 3.10. В любом случае или переходом на GTK3 или подпорками это решабельно:-)
 2. Что же касается мелкого текста в главном окошке, то офф. поддержка HiDPI в Chromium появилась только в 43ей версии: [No HiDPI support on Linux](https://code.google.com/p/chromium/issues/detail?id=143619). Старые костыли в виде ручной установки device-scale-factor в Chromium, к сожалению, работают не очень хорошо.  Brick базируется на стабильных версиях CEF и сейчас использует 41й Chromium, как только CEF выпустит новую стабильную ветку с свежим Хромом (должно быть довольно скоро) - этот вопрос должен решиться сам собой.

**Comment by MikhailBarsukov** [comment]
>Что же касается мелкого текста в главном окошке, то офф. поддержка HiDPI в Chromium появилась только в 43ей версии: No HiDPI support on Linux. Старые костыли в виде ручной установки device-scale-factor в Chromium, к сожалению, работают не очень хорошо. Brick базируется на стабильных версиях CEF и сейчас использует 41й Chromium, как только CEF выпустит новую стабильную ветку с свежим Хромом (должно быть довольно скоро) - этот вопрос должен решиться сам собой.
я правильно понимаю, что его уже добавили в 2357 бранче  https://bitbucket.org/chromiumembedded/cef/commits/branch/2357?

**Comment by buglloc** [comment]
> я правильно понимаю, что его уже добавили в 2357 бранче https://bitbucket.org/chromiumembedded/cef/commits/branch/2357?

Да, все верно. Там только возникли какие-то проблемы со сборкой у Adobe (даже на [cefbuilds.com](https://cefbuilds.com) пока не появился билд под Linux 64bit).
Решил подождать пока все устаканится и потом обновить, портировать патчи (для Brick пришлось немного пропатчить CEF) и протестить:-)

**Comment by buglloc** [comment]
Постарался сделать, что мог, со своей стороны, в 0.1.24.29 выйдет. Должно стать заметно лучше, но увы я не располагаю подобным девайсом для тестов поэтому не могу оценить user experience (не будет ли мыла и т.д.).
К сожалению, как и многие другие аппы будет себя не очень хорошо вести при разных настройках  у нескольких мониторов. Т.е. если один монитор WQXGA+, а второй FHD - scale factor определится по primary display и не будет пересчитан при перетаскивании окна между ними.

**Comment by MikhailBarsukov** [comment]
![2015-05-20 10_08_11](https://cloud.githubusercontent.com/assets/2105413/7720687/e45c108c-fed8-11e4-8117-15bdf8173fb6.png)

как стало.
Спасибо большое за закрытие бага/фичи. Всё теперь корректно.

**Comment by buglloc** [comment]
Ну вот и  чудненько:-) Кажется, не плохо выглядит.
Если будут еще какие-то проблемы при работе на HiDPI - пишите;) Я на будущее постараюсь учитывать их особенности, но, по понятным причинам, могу что-то упустить.
