### ISSUE TITLE
md5sum в AUR

### ISSUE THREAD

**Issue by co11ter** [buglloc/brick#14]
Здравствуйте! Не могу установить из aur:
```
$ yaourt -S brick
...
==> Проверка исходных файлов с помощью md5sums...
    v0.1.24.29.tar.gz ... Готово
    master.zip ... СБОЙ
==> ОШИБКА: Один или более файлов не прошли проверку целостности!
==> ERROR: Makepkg was unable to build brick.
==> Restart building brick ? [y/N]
```
 что-то не так с суммами...

**Comment by buglloc** [comment]
Подозрительно, видимо GitHub начал отдавать этот архив немного иначе из-за чего разошлась чексума.
Обновил PKGBUILD (brick 0.1.24.29-2), попробуйте пожалуйста сейчас.
Нужно будет чуть позже пересмотреть, может отказаться от master архива с libsodium вообще.
Спасибо вам:)

**Comment by co11ter** [comment]
Да, сейчас все встало и отлично работает, спасибо!

PS: Я подозреваю, что суммы будут разные на каждое изменение в мастере.
