### ISSUE TITLE
KDE tray icon

### ISSUE THREAD

**Issue by vmarijus** [buglloc/brick#22]
No tray icon in KDE (Linux Mint 17.2 Rafaela)
<img width="32" alt="screen shot 2015-10-01 at 08 06 07" src="https://cloud.githubusercontent.com/assets/14919088/10213256/4d72fd62-6813-11e5-8fd3-f97785dc4687.png">

**Comment by buglloc** [comment]
It seems there is a problem with support `libappindicator3-1`
Please, try to install `libappindicator1`

**Comment by buglloc** [comment]
Sorry, I was wrong. Is there a problem with the `icon-theme-path`, so KDE can't find the icon. Strange but i can't reproduce this problem on the Ubuntu/Kubuntu distributions.
Later, more detailed look.

**Comment by buglloc** [comment]
Please checkout version 0.2.4.31, KDE4 tray icon issue must be fixed
