### ISSUE TITLE
connection attempt failed

### ISSUE THREAD

**Issue by MikhailBarsukov** [buglloc/brick#24]
При попытке подключиться к серверу выдаёт A connection attempt failed (ERR_CONNECTION_FAILED/104). До этого обновился до 0.2.4.31
![screenshot from 2015-10-07 08 41 18](https://cloud.githubusercontent.com/assets/2105413/10329870/52361d8c-6ccf-11e5-8aaa-5d03b5d45cff.png)

**Comment by MikhailBarsukov** [comment]
![screenshot from 2015-10-07 08 44 40](https://cloud.githubusercontent.com/assets/2105413/10329893/aa4c6300-6ccf-11e5-9cca-1cc27c392329.png)

**Comment by buglloc** [comment]
Хм, не замечал проблем со своими серверами. При этом браузер благополучно открывает ваш портал? Это воспроизводится только на нашей машинке или коллеги еще не успели обновится?
Попробуйте:
   1. Закрыть Brick
   2. Очистить кеш `rm -rf ~/.cache/brick`
   3. Запустить снова

P.S. Если вы откатываетесь на 0.2.3.31 - проблема уходит? Найти предыдущий пакет, скорее всего, можно в кеше (для apt это `/var/cache/apt/archives/`)

**Comment by MikhailBarsukov** [comment]
> При этом браузер благополучно открывает ваш портал?
Да

> Это воспроизводится только на вашей машинке или коллеги еще не успели обновится?
нет, они не обновлялись ещё.

>Попробуйте:
>Закрыть Brick
>Очистить кеш rm -rf ~/.cache/brick
>Запустить снова
не помогло

>Если вы откатываетесь на 0.2.3.31 - проблема уходит?
да, заработало корректно.

**Comment by buglloc** [comment]
Интересно:)
Вы подключаетесь к порталу по http или https? Если по https, то не исключено что Chromium закрутил гайки чуть больше.

Не могли бы вы еще раз попробовать запустить новую версию и прислать лог (можно на почту) `~/.cache/brick/runtime.log` после получения ошибки?

**Comment by vmarijus** [comment]
Токая же проблема как у MikhailBarsukov. Ошибка "A connection attempt failed (ERR_CONNECTION_FAILED/104)." после обновления.

**Comment by MikhailBarsukov** [comment]
Работаем с порталом по https.
Логи сбросил на почту

**Comment by buglloc** [comment]
@MikhailBarsukov Спасибо! Логи помогли, для истории:
```
[1008/085119:ERROR:nss_ocsp.cc(613)] No URLRequestContext for NSS HTTP handler. host: [...]
[1008/085119:ERROR:cert_verify_proc_nss.cc(922)] CERT_PKIXVerifyCert for [...] failed err=-8179
[1008/085119:WARNING:auth_client.cc(111)] Auth request was canceled, probably SSL error
```
Смог воспроизвести на одной из машин, сваливается проверка отозванности сертификата по OCSP протоколу в виду чего запрос сбрасывается, а т.к. CEF не дает никакой доп. информации по этому поводу - Brick выводит generic сообщение об ошибке.

Постараюсь в скором времени отдебажить и выпустить обновление.

**Comment by buglloc** [comment]
Насколко я вижу проблема в не полной цепочке SSL сертификата отдаваемого сервером. В новых версиях (2454+) CEF сломалась установка SSL соединения при не полной цепочке: https://bitbucket.org/chromiumembedded/cef
Похоже связано с багом самого Chromium: https://code.google.com/p/chromium/issues/detail?id=539520

Чуть позже отдебажу/пропатчу CEF, но это отнюдь не быстро в виду самого процесса сборки.

Пока же наиболее логичным выглядят два варианта:
  1. Откатиться на версию 0.2.3.31
  2. Проверить свой сервер (например, с помощью SSLLabs: https://www.ssllabs.com/ssltest/analyze.html ) и в случае если цепочка не полна или он укажет на другие проблемы связанные с конфигурацией SSL вашего сервера - обратиться к администратору для исправления.

Проверить/устранить проблемы обозначенный SSLLabs я бы рекомендовал сделать в любом случае, вне зависимости от фиксов в Brick.

**Comment by buglloc** [comment]
Версия, с исправлением, `0.2.5.31` доступна в PPA и AUR.
Проверьте, пожалуйста, у себя помогло ль:)

**Comment by MikhailBarsukov** [comment]
Да, помогло. Спасибо!

**Comment by vmarijus** [comment]
Помогло. Спасибо! 

Marijus
