### ISSUE TITLE
A connection attempt failed (ERR_CONNECTION_FAILED/104)

### ISSUE THREAD

**Issue by aromarom64** [buglloc/brick#30]
Добрый день !

После добавления нового сертификата при коннекте стала появляться ошибка
A connection attempt failed (ERR_CONNECTION_FAILED/104)

в консоле только это
[1028/171141:WARNING:auth_client.cc(111)] Auth request was canceled, probably SSL error
Можно включить более детальное логирование ?

Через браузер захожу нормально.

Подскажите как можно пофиксить, привык уже пользоваться вашим клиентом, на браузер переходить не хочется.

Спасибо.

**Comment by buglloc** [comment]
Приветствую!
> Можно включить более детальное логирование ?
Я бы и рад, но на текущий момент CEF (Chromium Embedded Framework) на базе которого реализован Brick не отдает нужной информации, поэтому и в лог пишется "не уверенная" запись. Я записал себе фичу #25 что бы сделать патч и научить отдавать нужную информацию, но к сожалению это не столь быстро.

Теперь, что касается непосредственно проблем с авторизацией. Какая версия Brick? Если на этой же машине попробовать подключиться при помощи curl/httpie - они корректно устанавливают подключение?
Если нет, можно поробовать еще посмотреть при помощи `openssl s_client -connect Host:Port`, есть шанс, что он укажет на причину.
Если доступ к порталу открыт из вне, то так же хорошее средство диагностики - [Qualys SSL Labs](https://www.ssllabs.com/ssltest/)
И, если доступ открыт, то наиболее быстрый вариант был бы указать адрес портала - я попробую воспроизвести и посмотрю. Можно на почту buglloc [at] yandex.ru, если вам так удобнее.

**Comment by aromarom64** [comment]
Спасибо Вам за быстрый ответ. Ошибка была на моей стороне, нашел после проверки curl-ом с этого надо было и начинать, конечно. Оказывается у нас изменился не только сертификат.
Прошу прощение.

**Comment by buglloc** [comment]
Рад был помочь:)
