### ISSUE TITLE
By initialization app occur Error

### ISSUE THREAD

**Issue by clikman007** [buglloc/brick#32]
If i initialize app from console:
user@localhost:/tmp/brick/build# brick
[1118/164500:ERROR:dbus_protocol.cc(254)] Can't register D-BUS: Соединение закрыто
[1118/164500:INFO:account_manager.cc(141)] Empty accounts config: /root/.config/brick/accounts.json

**Comment by clikman007** [comment]
ОС: Debian 7, Gnome3

**Comment by buglloc** [comment]
I can't reproduce on Debian 7.9 :( Just install, update `libc6`, compile and run.

The rest of the application runs, or writes the errors and does not run?
Please try follows:
  1. Ensure chromium sandbox have SUID flag: `EXE="/opt/brick/bin/chrome-sandbox" && sudo -- chown root:root $EXE && sudo -- chmod 4755 $EXE`
  2. Your run `brick` from right (currently logged) user
  3. Ensure you have working D-Bus daemon, run `dbus-monitor --session` and start `brick`

**Comment by buglloc** [comment]
>> [1118/164500:INFO:account_manager.cc(141)] Empty accounts config: /root/.config/brick/accounts.json

Oh, I did not pay attention to this.
As I can see, you try to initialize `brick` from `root`, most likely not correct. Please try to open from proper (currently logged) user.

**Comment by clikman007** [comment]
Thanks, first item help me. And for info i install by source.

**Comment by buglloc** [comment]
Thanks for your reply. I'll check later why SUID flag for chromium sandbox may be missed while installing
