### ISSUE TITLE
Некорректная работа сообщений и звонков при разрыве соединения

### ISSUE THREAD

**Issue by RomanTesnikov** [buglloc/brick#4]
Ввиду настройки сервера портал разрывает подключение через небольшой промежуток времени, и в связи с этим в клиенте возникают ошибки.
При отправке сообщения в чате, Brick уведомляет о подключении к серверу, после чего перезагружается страница с чатом. При этом набранное сообщение не отправляется, и не сохраняется текст сообщения в поле ввода, приходится набирать сообщение заново.
При попытке совершить звонок, Brick в окне звонка уведомляет об ошибке авторизации (AUTHORIZE_ERROR), звонок совершить невозможно (решение - отправить что-нибудь в чате, чтобы Brick переподключился, после чего делать звонки).
Было бы неплохо, если бы Brick держал в фоне подключение активным или корректно отрабатывал при отсутствии подключения.

**Comment by buglloc** [comment]
> При отправке сообщения в чате, Brick уведомляет о подключении к серверу, после чего перезагружается страница с чатом.

Спасибо! Исправил, теперь при потере связи/авторизации страница должна заметно реже перезагружаться.

> При попытке совершить звонок, Brick в окне звонка уведомляет об ошибке авторизации (AUTHORIZE_ERROR), звонок совершить невозможно (решение - отправить что-нибудь в чате, чтобы Brick переподключился, после чего делать звонки).

Я еще раз перепроверю, но это скорее на стороне модуля Битрикс "Веб-мессенджер". Мы побеседовали с автором и нашли одну особенность, которая потенциально затрагивает и приведенный вами кейс. Исправление выйдет в одном из ближайших обновлений модуля.

> Ввиду настройки сервера портал разрывает подключение через небольшой промежуток времени, и в связи с этим в клиенте возникают ошибки.

Поясните, пожалуйста, детальнее что вы имеете в виду. Смотрите, Brick - это гибридное приложение. Он держит LongPooling коннект к nignx (если у вас коробка и используется модуль пулинга) и для каких-то действий посылает http-запросы к PHP (в том числе, периодически продлевая PHP-сессию).
И тут возможны варианты:
1. У вас истекает сессия, тогда нужно смотреть почему не отрабатывает встроенный механизм продления. 
2. Через какое-то время пуллинг сервер отказывается принимать подключения.
