### ISSUE TITLE
Белое (пустое) окно

### ISSUE THREAD

**Issue by GreenRobot777** [buglloc/brick#42]
```
Sabayon Linux 16.2 x64
KDE Plasma 5.4.4
Qt: 5.5.1
Core: 4.4.0-sabayon
```

Собирал brick вручную по инструкции с readme

При попытке запуска brick появляется белое окно и следующие ошибки в консоли:
$ brick

[0306/161618:INFO:dbus_protocol.cc(150)] Acquired the bus org.brick.Brick
[0306/161618:INFO:account_manager.cc(141)] Empty accounts config: /home/greenrobot/.config/brick/accounts.json
[0306/161618:INFO:notification_manager_linux.cc(274)] Notification server supports actions
[0306/161619:FATAL:memory_linux.cc(43)] Out of memory.

**Comment by GreenRobot777** [comment]
UPD: Авторизоваться получилось (через появившийся значок в трее), но после авторизации окно по-прежнему пустое.

**Comment by buglloc** [comment]
Спасибо, воспроизвел!
Пожалуйста, попробуйте запулить правки и пересобрать:
```
cd ~/tmp/build
git pull
make
sudo make install
```
Должно помочь.
Заметил еще одну странность - "не подцепилать" иконка в трее, отображается какая-то из дефолтного набора KDE? У вас тоже? Если да - откройте, пожалуйста, еще один тикет, я чуть позже посмотрю в чем может быть дело.

**Comment by GreenRobot777** [comment]
Отлично! Помогло!

Не знаю какая должна быть иконка, у меня в "трее" KDE вот такая:
![image](https://cloud.githubusercontent.com/assets/14993551/13898474/1daf0c32-edfc-11e5-9a66-acab1c848a59.png)

**Comment by buglloc** [comment]
> Отлично! Помогло! Тикет можно закрывать.

Отлично:)

> Не знаю какая должна быть иконка, у меня в "трее" KDE вот такая:

Это не правильная, я чуть позже посмотрю почему это произошло. Можете пока создать отдельный тикет по поводу иконки? Правильная выглядит [как-то так](https://github.com/buglloc/brick/blob/master/Resources/indicator/icons/online.svg).
Соответственно, скорее всего, и остальные, более важные, иконки тоже не работают (Приход нового сообщения, уведомления и т.д.)
