### ISSUE TITLE
при сборке в Debian Jessie

### ISSUE THREAD

**Issue by albel4** [buglloc/brick#46]
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:155 (APPEND_PLATFORM_SOURCES):
  Unknown CMake command "APPEND_PLATFORM_SOURCES".

**Comment by buglloc** [comment]
Вы точно запускаете cmake для нужной директории? Можете привести полную посследовательность комманд, которые вы выполняете?
Обычно, эта ошибка связана с тем что cmake запустился не в корневой директории проекта.

**Comment by albel4** [comment]
Делал по инструкции:

# Let's make it
mkdir ~/tmp && cd ~/tmp
git clone --recursive https://github.com/buglloc/brick.git
mkdir build && cd build
cmake ../brick


12 июня 2016 г., 11:37 пользователь Andrew Krasichkov <
notifications@github.com> написал:

**Comment by albel4** [comment]
Хотя не совсем точно по инструкции. По инструкции только последняя часть.
mkdir build && cd build
cmake ../brick


12 июня 2016 г., 11:37 пользователь Andrew Krasichkov <
notifications@github.com> написал:

**Comment by albel4** [comment]
Пробовал по инструкции, cmake пытается ещё что-то загрузить, но из-за прокси с авторизацией у него ничего не получается. Есть метод полностью ручной сборки? Я сам скачаю всё необходимое, разложу по полочкам. А уж cmake пусть собирает.

**Comment by buglloc** [comment]
> Есть метод полностью ручной сборки? Я сам скачаю всё необходимое, разложу по полочкам. А уж cmake пусть собирает.

Да, вам нужно скачать набор заранее собранных библиотек (они поставляются в бинарном виде, ибо их сборка занимает порядка 4 часов) и положить в папку "Release" кореня проекта. Их есть две версии, в зависимости от вашей архитектуры.
Для 64 битной платформы: https://github.com/buglloc/cef-builds/raw/0d15971961fda87682bd5e067cdcf5450e72b6b8/libs/cef-x86_64.tar.gz
Для 32х: https://github.com/buglloc/cef-builds/raw/0d15971961fda87682bd5e067cdcf5450e72b6b8/libs/cef-i686.tar.gz

Весь процесс выглядит как-то так (у меня x86_64, добавилось пару шагов):
```bash
mkdir ~/tmp && cd ~/tmp
git clone https://github.com/buglloc/brick.git

mkdir brick/Release
wget https://github.com/buglloc/cef-builds/raw/0d15971961fda87682bd5e067cdcf5450e72b6b8/libs/cef-x86_64.tar.gz
tar zxf cef-x86_64.tar.gz -C brick/Release

mkdir build && cd build
cmake ../brick
make
sudo make install
```

**Comment by chessim** [comment]
Прекрасно собирается из исходников после добавления deb-src:
[https://wiki.debian.org/CreatePackageFromPPA](url)
