### ISSUE TITLE
Не даёт зайти в портал

### ISSUE THREAD

**Issue by kosas** [buglloc/brick#51]
У нас есть сотрудник ( Игорь Налетов) у которого после последнего сбоя десктоп приложение (BRICK) не пускает в наш портал kosas.bitrix24.ru 

Дело не приложении, т.к. с этого же компьютера данный сотрудник может зайти на 10 порталов через (Brick) это же приложение. 

http://storage4.static.itmages.com/i/16/0727/h_1469611522_1145367_d32f8dd793.jpeg
http://storage8.static.itmages.com/i/16/0727/h_1469612218_8998195_eb6e3ab7d2.jpeg

Не помогает переустановка Хрома, удаление учетной записи, чистка кэшей и прочее.
Где и что можно почистить?

**Comment by buglloc** [comment]
Отправте, пожалуйста, мне на почту лог (`~/.cache/brick/runtime.log`), попробую посмотреть в чем дело. Выглядит странно - аутентификация прошла (иначе Brick показал бы ошибку), но потом что-то пошло не так.
Так же можно попробовать очистить все настройки и кеш:
```
rm -rf ~/.config/brick/
rm -rf ~/.cache/brick/
```

**Comment by kosas** [comment]
Благодарю. Очистка конфига помогла.
