### ISSUE TITLE
LDAP авторизация

### ISSUE THREAD

**Issue by denisbutov** [buglloc/brick#56]
Пользователи, созданные в Битрикс, заходят нормально. Если для пользователя используется LDAP авторизация, зайти под ним через приложение не получится.

**Comment by buglloc** [comment]
Если кратко - видимо модуль LDAP-авторизации не научился работать с паролями приложений.

Если это так, то есть два варианта:
- добавить обработчик событий, что бы он мог в пароли приложений: https://github.com/buglloc/brick/issues/3#issuecomment-93979922
- не использовать их при аутентификации: снять галку "Use App Password" в настройках аккаунта

**Comment by denisbutov** [comment]
Спасибо Вам огромное за работу.
