### ISSUE TITLE
ArchLinux

### ISSUE THREAD

**Issue by co11ter** [buglloc/brick#6]
Слышал о возможной поддержке ArchLinux. Это будет скоро или имеет смысл самому писать PKGBUILD?

**Comment by buglloc** [comment]
Да, я планировал сделать PKGBUILD для AUR, т.к. сам пользуюсь ArchLinux как основным дистрибутивом.
Со сроками, увы, сложнее.
По пессимистичным оценкам - до конца мая.
По оптимистичным - до конца апреля, думал заняться этим на следующих выходных вместе с корректными install правилами для CMake, если не возникнет чего более критичного.

**Comment by buglloc** [comment]
Как и обещал, переделал процесс сборки, перебрал install правила в CMake и теперь сборка стала проще и лаконичнее.
Поэтому Brick появился и в AUR: https://aur.archlinux.org/packages/brick/
Попробуйте, должно корректно собираться и устанавливаться.

P.S. Может чуть позже еще раз пересмотрю его, что бы избавится от кастомного libsodium в пользу системного
P.S.S. Пакет brick-unity пока не собирал, чуть позже займусь. Не думаю что он очень уж популярен
