### ISSUE TITLE
Онлайн статус из brick не синхронизируется с xmpp сервером

### ISSUE THREAD

**Issue by MikhailBarsukov** [buglloc/brick#8]
Статус "онлайн" выставленный в brick не даётся в список сотрудников, подключенных к XMPP серверу битрикса. То есть работая только в brick, сотрудники в jabber видят мой статус offline

**Comment by buglloc** [comment]
А при этому в веб-мессенджере (браузере) ваш статус у коллег показывается корректный?
Нет ли у вас возможности попросить кого-то из коллег воспроизвести этот же эффект с оффициальным клиентом под Windows/Mac? Дело в том, что этой частью управляет не Brick, а JS код модуля im. Поэтому как-то даже не знаю с какой стороны прицепиться.
Если эта же проблема воспроизводится и на оффициальных клиентах от Битрикс, то скорее дело в самом Битрикс.

P.S. На своем рабочем портале не воспроизвожу, коллеги видят корректный статус:-(

**Comment by MikhailBarsukov** [comment]
Возможно был баг с настройками самого битрикса. Воспроизвести сами теперь не можем. Пока закрываю, спасибо!
