### ISSUE TITLE
Not working on Mint 19 - x86_64

### ISSUE THREAD

**Issue by barrosohub** [buglloc/brick#93]
Screen empty after init a call

**Comment by javeteam** [comment]
Try this https://github.com/buglloc/brick/issues/67#issuecomment-350572237

**Comment by ayushpahwa** [comment]
Unable to add ppa in Mint 19 \
`> sudo add-apt-repository ppa:buglloc/brick`
`HTTP Error 404: Not Found`
`Cannot add PPA: ''This PPA does not support bionic''.
`

**Comment by javeteam** [comment]
> Unable to add ppa in Mint 19 
> `> sudo add-apt-repository ppa:buglloc/brick`
> `HTTP Error 404: Not Found`
> `Cannot add PPA: ''This PPA does not support bionic''. `

sudo echo "deb http://ppa.launchpad.net/buglloc/brick/ubuntu xenial main" > /etc/apt/sources.list.d/buglloc-ubuntu-brick-bionic.list
sudo apt-get update && apt-get install brick

**Comment by MelnykovOleksii** [comment]
> sudo echo "deb http://ppa.launchpad.net/buglloc/brick/ubuntu xenial main" > /etc/apt/sources.list.d/buglloc-ubuntu-brick-bionic.list

не сработало, но сработало так: 
`sudo su -c "echo 'deb http://ppa.launchpad.net/buglloc/brick/ubuntu xenial main' > /etc/apt/sources.list.d/buglloc-ubuntu-brick-bionic.list"`

Но при `sudo apt-get update && apt-get install brick` выдаёт:
```
Err:8 http://ppa.launchpad.net/buglloc/brick/ubuntu xenial InRelease
The following signatures couldn't be verified because the public key is not available: NO_PUBKEY
W: GPG error: http://ppa.launchpad.net/buglloc/brick/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY
E: The repository 'http://ppa.launchpad.net/buglloc/brick/ubuntu xenial InRelease' is not signed.
```

**Comment by panaceya** [comment]
> > sudo echo "deb http://ppa.launchpad.net/buglloc/brick/ubuntu xenial main" > /etc/apt/sources.list.d/buglloc-ubuntu-brick-bionic.list
> 
> не сработало, но сработало так:
> sudo su -c "echo 'deb http://ppa.launchpad.net/buglloc/brick/ubuntu xenial main' > /etc/apt/sources.list.d/buglloc-ubuntu-brick-bionic.list"
> 
> Но при sudo apt-get update && apt-get install brick выдаёт:
> Err:8 http://ppa.launchpad.net/buglloc/brick/ubuntu xenial InRelease
> The following signatures couldn't be verified because the public key is not available: NO_PUBKEY
> W: GPG error: http://ppa.launchpad.net/buglloc/brick/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY
> E: The repository 'http://ppa.launchpad.net/buglloc/brick/ubuntu xenial InRelease' is not signed.

Этого будет достаточно
`cat /etc/apt/sources.list.d/buglloc-ubuntu-brick-xenial.list`:
```
deb http://ppa.launchpad.net/buglloc/brick/ubuntu xenial main
# deb-src http://ppa.launchpad.net/buglloc/brick/ubuntu xenial main
```

PS: мне на 18.04 пришлось собирать из исходников, т.к. приложение крашилось.

**Comment by MelnykovOleksii** [comment]
> Этого будет достаточно
> `cat /etc/apt/sources.list.d/buglloc-ubuntu-brick-xenial.list`:
> 
> ```
> deb http://ppa.launchpad.net/buglloc/brick/ubuntu xenial main
> # deb-src http://ppa.launchpad.net/buglloc/brick/ubuntu xenial main
> ```
> 
> PS: мне на 18.04 пришлось собирать из исходников, т.к. приложение крашилось.

Извини, но я тебя не понял.
у меня Mint v19.1
